/**
 * Regenerates the checked-in baseline catalog from models.dev.
 *
 *   pnpm --filter @repo/models sync
 *
 * Fetches https://models.dev/api.json, filters to the curated provider allowlist
 * (src/llm-catalog/providers.ts), transforms each entry into LlmCatalogModel via
 * the shared pure transform, and writes src/llm-catalog/models.generated.ts.
 *
 * The same transform is reused at runtime by the backend ModelCatalog live
 * overlay, so the generated file is purely an offline-safe baseline. Run this
 * whenever you want to refresh the committed snapshot (and review the diff).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import type { ModelsDevResponse } from '@repo/types';
import { LLM_PROVIDERS } from '../src/llm-catalog/providers.js';
import { MODELS_DEV_API_URL, transformModelsDev } from '../src/llm-catalog/transform.js';

const OUT_FILE = join(
	dirname(fileURLToPath(import.meta.url)),
	'..',
	'src',
	'llm-catalog',
	'models.generated.ts',
);

async function main(): Promise<void> {
	console.log(`[models:sync] fetching ${MODELS_DEV_API_URL} …`);
	const res = await fetch(MODELS_DEV_API_URL);
	if (!res.ok) {
		throw new Error(`models.dev responded ${res.status} ${res.statusText}`);
	}
	const raw = (await res.json()) as ModelsDevResponse;

	const models = transformModelsDev(raw, LLM_PROVIDERS);
	if (models.length === 0) {
		throw new Error('transform produced 0 models — aborting (allowlist/key mismatch?)');
	}

	const byProvider = new Map<string, number>();
	for (const m of models) byProvider.set(m.providerId, (byProvider.get(m.providerId) ?? 0) + 1);

	const header = `// AUTO-GENERATED by \`pnpm --filter @repo/models sync\` — DO NOT EDIT BY HAND.
// Source: ${MODELS_DEV_API_URL}
// Providers: ${[...byProvider.entries()].map(([p, n]) => `${p}(${n})`).join(', ')}
// Total: ${models.length} models.
import type { LlmCatalogModel } from '@repo/types';

export const LLM_MODELS: LlmCatalogModel[] = ${JSON.stringify(models, null, '\t')};
`;

	writeFileSync(OUT_FILE, header, 'utf8');
	console.log(`[models:sync] wrote ${models.length} models → ${OUT_FILE}`);
	for (const [p, n] of byProvider) console.log(`  ${p}: ${n}`);
}

main().catch((err: unknown) => {
	console.error('[models:sync] failed:', err instanceof Error ? err.message : err);
	process.exit(1);
});
